/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-12-15 16:59:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import pe.dto.Students;

public final class studentList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Student/Student/build/web/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1701074286358L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("pe.dto.Students");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Admin Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <h1>Welcome  to the student list page</h1>\n");
      out.write("    </body>\n");
      out.write("    <form action=\"MainController\">\n");
      out.write("        <input name=\"action\" type=\"submit\" value=\"Logout\" />\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <form action=\"MainController\">\n");
      out.write("        <input type=\"text\" name=\"data\" />\n");
      out.write("        <input type=\"submit\" value=\"search\" name=\"action\" /> \n");
      out.write("    </form>\n");
      out.write("    <table border=\"1\">\n");
      out.write("        <thead>\n");
      out.write("            <tr>\n");
      out.write("                <th>No</th>\n");
      out.write("                <th>id</th>\n");
      out.write("                <th>name</th>\n");
      out.write("                <th>major</th>\n");
      out.write("                <th>year of birth</th>\n");
      out.write("                <th>Delete</th>\n");
      out.write("                <th>Update</th>\n");
      out.write("            </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("            ");

                int count = 0;
                List<Students> list = (List) request.getAttribute("list");
                if (list != null) {
                    for (Students i : list) {
                        count++;
            
      out.write("\n");
      out.write("        <form action=\"MainController\" method=\"POST\">\n");
      out.write("            <tr>\n");
      out.write("                <td>");
      out.print(count);
      out.write("</td>\n");
      out.write("                <td>");
      out.print( i.getId());
      out.write("</td>\n");
      out.write("                <td><input type=\"text\" name=\"name\" value=\"");
      out.print( i.getName());
      out.write("\"></td>\n");
      out.write("                <td><input type=\"text\" name=\"major\" value=\"");
      out.print( i.getMajor());
      out.write("\"></td>\n");
      out.write("                <td><input type=\"text\" name=\"yearOfBirth\" value=\"");
      out.print( i.getYearOfBirth());
      out.write("\" readonly=\"\"></td>\n");
      out.write("                <td>\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( i.getId());
      out.write("\">\n");
      out.write("                    <a href=\"MainController?action=delete&id=");
      out.print( i.getId());
      out.write("\" >Delete</a>\n");
      out.write("                </td>\n");
      out.write("                <td>\n");
      out.write("                    <input type=\"submit\" name=\"action\" value=\"update\">\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        </form>\n");
      out.write("    </tbody>\n");
      out.write("    ");
 }
        }
      out.write("\n");
      out.write("</table>\n");
      out.write("<form action=\"studentList.jsp\" method=\"POST\">\n");
      out.write("    <input type=\"submit\" name=\"status\" value=\"add\">\n");
      out.write("</form>\n");
 String status = request.getParameter("status");
    if (status != null && status.equals("add")) {

      out.write("\n");
      out.write("<h1>Add New Student</h1>\n");
      out.write("<form action=\"MainController\" method=\"POST\">\n");
      out.write("    ID: <input type=\"text\" name=\"id\" required=\"\"><br>\n");
      out.write("    Name: <input type=\"text\" name=\"name\" required=\"\"><br>\n");
      out.write("    Major: <input type=\"text\" name=\"major\" required=\"\"><br>\n");
      out.write("    Year Of Birth :<input type=\"number\" name=\"yearOfBirth\" required=\"\"><br>\n");
      out.write("    <input type=\"submit\" name=\"action\" value=\"save\">\n");
      out.write("</form>\n");
}
      out.write("\n");
      out.write("<p style=\"background-color: green; margin-top:20px;color:white;display:inline-block;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noti}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
