/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-11-27 07:44:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Sneaker Store</title>\r\n");
      out.write("        <link href=\"//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <h1>Welcome Sneaker Store</h1>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"box-container\">\r\n");
      out.write("            <img id=\"myImage\" src=\"img/Air Jordan 1 Mid SE .jpg\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"MainController\" method=\"POST\">\r\n");
      out.write("            <div class=\"col-md-6\"  style=\"background-color:#e88d8d;\r\n");
      out.write("                 background-image: linear-gradient(160deg, #e88d8d 0%, #e88d8d 100%);\r\n");
      out.write("                 \">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <select name=\"cmbProduct\" >\r\n");
      out.write("                    <option  value=\"S01-Air Jordan 1 Mid SE-Nike-3959000-41\">Air Jordan 1 Mid SE - 3959000$</option>\r\n");
      out.write("                    <option  value=\"S02-Air Jordan 1 Mid SE Craft-Nike-3959000-40\">Air Jordan 1 Mid SE Craft - 3959000$</option>\r\n");
      out.write("                    <option  value=\"S03-Air Jordan 1 Mid-Nike-3669000-43\">Air Jordan 1 Mid- 3669000$</option>\r\n");
      out.write("                    <option  value=\"S04-ULTRABOOST-Adidas-4500000-43\">ULTRABOOST - 4500000$</option>\r\n");
      out.write("                    <option  value=\"S05-SUPERSTAR-Adidas-2600000-43\">SUPERSTAR - 2600000$</option>\r\n");
      out.write("                    <option  value=\"S06-STAN SMITH-Adidas-2600000-44\">STAN SMITH - 2600000$</option>\r\n");
      out.write("                    <option  value=\"S07-VANS ERA CLASSIC BLACK-VANS-1450000-42\">VANS ERA CLASSIC BLACK - 1450000$</option>\r\n");
      out.write("                    <option  value=\"S08-Converse Chuck 70 Black-Converse-2000000-41\">Converse Chuck 70 Black - 2000000$</option>\r\n");
      out.write("                </select>\r\n");
      out.write("\r\n");
      out.write("                <select name=\"cmbQuantity\">\r\n");
      out.write("                    <option value=\"1\">1</option>\r\n");
      out.write("                    <option value=\"2\">2</option>\r\n");
      out.write("                    <option value=\"3\">3 </option>\r\n");
      out.write("                    <option value=\"5\">5</option>\r\n");
      out.write("                    <option value=\"10\">10</option>\r\n");
      out.write("                    <option value=\"100\">100</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\" style=\"background-color: #e88d8d;\r\n");
      out.write("                 background-image: linear-gradient(160deg, #e88d8d 0%, #e88d8d 100%);\r\n");
      out.write("                 \">\r\n");
      out.write("                <input type=\"submit\" name=\"action\" value=\"Logout\">\r\n");
      out.write("                <input type=\"submit\" name=\"action\" value=\"Add\"/>\r\n");
      out.write("                <input type=\"submit\" name=\"action\" value=\"View\"/></br>\r\n");
      out.write("               ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.MESSAGE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    body{\r\n");
      out.write("        background-image: #f4cccc;\r\n");
      out.write("        background: #f4cccc;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    h1{\r\n");
      out.write("        color: burlywood;\r\n");
      out.write("        font-family: fantasy;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 50px 0;\r\n");
      out.write("        margin: 0 180px;\r\n");
      out.write("        font-size: 40px;\r\n");
      out.write("    }\r\n");
      out.write("    h5{\r\n");
      out.write("        overflow-x: hidden;\r\n");
      out.write("        font-family: fantasy;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 26.5px;\r\n");
      out.write("        margin: 0 88px;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    .row{\r\n");
      out.write("        margin-top: 20px; \r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        font-family: cursive;\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("    }\r\n");
      out.write("    .col-md-6{\r\n");
      out.write("\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        box-shadow: 0px 0px 10px black;            \r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 20px 0;\r\n");
      out.write("        background-color: ghostwhite;\r\n");
      out.write("        width: 35%;\r\n");
      out.write("        margin-left: 100px;\r\n");
      out.write("    }\r\n");
      out.write("    .col-md-6 input{\r\n");
      out.write("        width: 25%;\r\n");
      out.write("    }\r\n");
      out.write("    #myImage{\r\n");
      out.write("\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        width: 600px;\r\n");
      out.write("        height: 413px;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        bottom: 0; \r\n");
      out.write("        text-align: center;\r\n");
      out.write("        align-content: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("    .footer{\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        overflow-x: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    .box-container{\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
